---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld-tf
spec:
  interval: 1m
  url: https://github.com/pmmenezes/tf-controller-helloworld
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
spec:
  healthChecks:  
    name: Teste
    type: http
    url: https://github.com/pmmenezes/tf-controller-helloworld
  path: ./terraform
  approvePlan: auto
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
  writeOutputsToSecret:
    name: helloworld-outputs
